### ISSUE TITLE
Will it work with Redmine 3.x?

### ISSUE THREAD

**Issue by jaimestuardo** [cdwertmann/recaptcha#2]
I have installed this plugin in my Redmine, but I get this error in log file:

```
Processing by AccountController#register as HTML
  Current user: anonymous
  Rendered plugins/recaptcha/app/views/account/register.html.erb within layouts/base (3.6ms)
Completed 500 Internal Server Error in 7ms (ActiveRecord: 0.3ms)

ActionView::Template::Error (No private key specified.):
    26:   <p><%= custom_field_tag_with_label :user, value %></p>
    27: <% end %>
    28:
    29: <%= recaptcha_tags :public_key => Setting.plugin_recaptcha['recaptcha_public_key'], :ssl => true %>
    30: </div>
    31:
    32: <%= submit_tag l(:button_submit) %>
  app/helpers/application_helper.rb:1027:in `labelled_form_for'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

Is this a compatibility issue or something else?

Regards
Jaime

**Comment by cdwertmann** [comment]
> ActionView::Template::Error (No private key specified.):

Did you enter your recaptcha key?

**Comment by jaimestuardo** [comment]
Of course:

![image](https://cloud.githubusercontent.com/assets/9195659/15179721/f98be8d0-1753-11e6-9cd1-2907503d3e2c.png)

Public key was "Site key" and private key was "Secret key". That is named by recaptcha page.

**Comment by hameno** [comment]
Have the same problem...

**Comment by eckucukoglu** [comment]
by the way, I'm using this plugin for Redmine v3.3.0 w/o any problems.

**Comment by dgeo** [comment]
@hameno @jaimestuardo same here, fixed by pull request #5 for me.

It seems to depend on recaptcha gem version, my pull request let it work with latest.

(no ruby skills here, but it may need a version in Gemfile ?)

**Comment by danaivehr** [comment]
Works on 3.4.0.
Thank you for your plugin!

**Comment by jcormier** [comment]
Works on 4.1.3

**Comment by intractabilis** [comment]
On 5.0.3 I had to change
```
require 'account_controller_patch'
```
to
```
require_relative 'lib/account_controller_patch'
```
otherwise it couldn't load `account_controller_patch`.

However, now I am getting the following error:
```
Error: The application encountered the following error: uninitialized constant AccountControllerPatch

    parent.const_get(cname, false)
          ^^^^^^^^^^ (NameError)
```

Any ideas?

**Comment by intractabilis** [comment]
I tried renaming `AccountControllerRecaptchaPatch` to `AccountControllerPatch`. The plugin loaded, but `https://server/account/register` page shows 

![изображение](https://user-images.githubusercontent.com/45959195/206266610-c536aad8-0302-4e65-81ab-87cfbceca3a5.png)

I couldn't find any error messages in the Apache log files.

**Comment by ecsv** [comment]
It should work in theory with redmine 5.0.4 using the current master branch
