### ISSUE TITLE
Plugin don't work ArgumentError (undefined class/module ActionController::Parameters):

### ISSUE THREAD

**Issue by mtolava** [cdwertmann/recaptcha#6]
Hello.
I have troubles with my Redmine. When a user want to register redmine show him the 500 error page. When I want to setup the plugin redmine show it to me too. Somebody had the same problem?

The setup of my server is:
```
Environment:
  Redmine version    2.6.10.stable.15413
  Ruby version          2.2.4-p230 (2015-12-16) [i686-linux]
  Rails version          3.2.22.2
  Environment          production
  Database adapter Mysql2
SCM:
  Subversion               1.8.8
  Git                            1.9.1
  Filesystem                     
  Xitolite                       1.9.1
Redmine plugins:
  dpi_cmi                                       0.0.3
  recaptcha                                   1.0.0
  redmine_bootstrap_kit                0.2.4
  redmine_git_hosting                   1.2.1
  redmine_google_calendar          0.2.0
  redmine_information                  1.0.2
  redmine_knowledgebase           3.0.7
  redmine_monitoring_controlling 0.1.1
  redmine_reminder                      0.1.2
  timelog_timer                              2.0.0

```
The error when I want to setup the plugin is:
```
Started GET "/settings/plugin/recaptcha" for ###.###.###.### at 2017-03-28 09:50:56 -0300
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"recaptcha"}
  Current user: 
Completed 500 Internal Server Error in 7.8ms

ArgumentError (undefined class/module ActionController::Parameters):
  app/models/setting.rb:98:in `value'
  app/models/setting.rb:113:in `[]'
  app/models/setting.rb:142:in `plugin_recaptcha'
  app/controllers/settings_controller.rb:69:in `plugin'
```

and when a user want to register is
```

Started GET "/account/register" for ###.###.###.### at 2017-03-28 11:05:29 -0300
Processing by AccountController#register as HTML
  Current user: anonymous
  Rendered plugins/recaptcha/app/views/account/register.html.erb within layouts/base (143.4ms)
Completed 500 Internal Server Error in 175.3ms

ActionView::Template::Error (undefined class/module ActionController::Parameters):
    29:   <p><%= custom_field_tag_with_label :user, value %></p>
    30: <% end %>
    31: 
    32: <%= recaptcha_tags :public_key => Setting.plugin_recaptcha['recaptcha_public_key'], :ssl => true %>
    33: </div>
    34: 
    35: <%= submit_tag l(:button_submit) %>
  app/models/setting.rb:98:in `value'
  app/models/setting.rb:113:in `[]'
  app/models/setting.rb:142:in `plugin_recaptcha'
  app/helpers/application_helper.rb:1056:in `labelled_form_for'
```

**Comment by mtolava** [comment]
We saw the archive register.html.erb (from plugin) is diferent to register.html.erb (to redmine) and change it but havent solve the problem.

Select language in the plugin
`19: <p><%= f.select :language, lang_options_for_select %></p>`

Select language in redmine
``` 
20: <% unless @user.force_default_language? %>
21: <p><%= f.select :language, lang_options_for_select %></p>
22: <% end %>
```
